version: "3"

services:
  spark-master:
    image: ml-pyspark:latest
    build: .
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./scripts:/scripts
      - ./data:/app/data
      - ./models:/app/models
      - ./config/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    command: ["/scripts/master-entrypoint.sh"]

  spark-worker:
    image: ml-pyspark:latest
    build: .
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./scripts:/scripts
      - ./data:/app/data
      - ./models:/app/models
      - ./config/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    command: ["/scripts/worker-entrypoint.sh"]
    deploy:
      mode: replicated
      replicas: 2

  ml-application:
    image: ml-pyspark:latest
    build: .
    depends_on:
      - spark-master
    volumes:
      - ./scripts:/scripts
      - ./data:/app/data
      - ./models:/app/models
      - ./notebooks:/app/notebooks
      - ./config/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    command: ["python", "/app/src/models/train_model.py"]

volumes:
  scripts:
  data:
  models:
