name: Schedule model Retraining
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  restrain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11.2
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Retrain model
        run: python src/models/train_model.py
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add models/
          git commit -m "(bot): Retrain model and update model file" || echo "No changes to commit"
          git push
